name: pyshop_task_camera_app
description: "tech task for pyshop where i have to make a photo taking app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-238.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  intl: ^0.19.0
  permission_handler: ^11.3.0
  envied: ^0.5.3
  json_annotation: ^4.8.1
  dio: ^5.4.2+1
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.9
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  envied_generator: ^0.5.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/home_screen.jpg
